driver: chrome
options:
  experimental:
    - mobileEmulation: 
        deviceMetrics:
          width: 360
          height: 640
          pixelRatio: 3.0
        userAgent: Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19
        clientHints:
          platform: Android
          mobile: True
    - windowTypes: ["webview"]
service:
  executable_path: <path_to_driver>