driver: chrome
options:
  experimental:
    - mobileEmulation: 
        deviceMetrics:
          width: 430
          height: 932
          pixelRatio: 3.0
        userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/605.1 NAVER(inapp; search; 2000; 12.12.50; 14PROMAX)
        clientHints:
          platform: iOS
          mobile: True
    - windowTypes: ["webview"]
service:
  executable_path: <path_to_driver>